const SearchTypes={
    FETCHING_SEARCH_DATA_START:"FETCHING_SEARCH_DATA_START",
    FETCHING_SEARCH_DATA_SUCCESS:"FETCHING_SEARCH_DATA_SUCCESS",
    FETCHING_SEARCH_DATA_FAILURE:"FETCHING_SEARCH_DATA_FAILURE",
    ADD_TO_SEARCH_FIELD:"ADD_TO_SEARCH_FIELD",
    REMOVE_FROM_SEARCH_FIELD:"REMOVE_FROM_SEARCH_FIELD"
};

export default SearchTypes;