const ContentTypes={
FETCH_CONTENT_START:"FETCH_CONTENT_START",
FETCH_CONTENT_SUCCESS:"FETCH_CONTENT_SUCCESS",
FETCH_CONTENT_FAILURE:"FETCH_CONTENT_FAILURE",
MOVIE_FETCHING_START:"MOVIE_FETCHING_START",
MOVIE_FETCHING_SUCCESS:"MOVIE_FETCHING_SUCCESS",
MOVIE_FETCHING_FAILURE:"MOVIE_FETCHING_FAILURE",
MOVIE_FETCHING_RECOMS:"MOVIE_FETCHING_RECOMS",
LOCATION_CHANGE:"LOCATION_CHANGE"

}

export default ContentTypes;