const userTypes={
    FETCH_ACTIVE_CEREDENTIALS:"FETCH_ACTIVE_CEREDENTIALS",
    SET_LOGIN_DATA:"SET_LOGIN_DATA",
    ERROR_ON_FETCHING_DATA:"ERROR_ON_FETCHING_DATA",
    CHECK_USER_ACTIVATE:"CHECK_USER_ACTIVATE",
    CHECK_USER_SUCCESS:"CHECK_USER_SUCCESS",
    CHECK_USER_FAILURE:"CHECK_USER_FAILURE",
    ADD_USER_PROFILE:"ADD_USER_PROFILE"
}

export default userTypes;